server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          # uri: https://github.com/amigo1975/microsevices-data-project
          # ANALIZAR SI TERMINA EN .git O NO
          uri: https://github.com/daniel-eguiluz/tarea2tingeso.git
          search-paths: config-data
  application:
    name: config-service
